name: macOS .app build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyinstaller

      - name: Build .app with PyInstaller
        run: |
          pyinstaller --noconfirm --name "IPTV-MAC-STALKER-PLAYER" --windowed \
            --collect-submodules PyQt6 --collect-data PyQt6 \
            --collect-submodules PyQt5 --collect-data PyQt5 \
            --collect-submodules telethon --collect-data telethon \
            "STALKER PLAYER.py"

      - name: Ad-hoc sign (not notarized)
        run: |
          /usr/bin/codesign --force --deep --sign - "dist/IPTV-MAC-STALKER-PLAYER.app" || true

      - name: Zip the .app
        run: |
          cd dist && zip -r IPTV-MAC-STALKER-PLAYER-mac.zip "IPTV-MAC-STALKER-PLAYER.app"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IPTV-MAC-STALKER-PLAYER-mac
          path: dist/IPTV-MAC-STALKER-PLAYER-mac.zip
