name: Build macOS App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install "pyinstaller>=6.10"

      - name: Build .app with PyInstaller (exclude QtBluetooth)
        run: |
          pyinstaller --clean --noconfirm --name "IPTV-MAC-STALKER-PLAYER" --windowed \
            --collect-submodules PyQt6 --collect-data PyQt6 \
            --exclude-module PyQt6.QtBluetooth \
            "STALKER PLAYER.py"

      - name: Upload macOS .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: IPTV-MAC-STALKER-PLAYER-macOS
          path: dist/IPTV-MAC-STALKER-PLAYER.app
