name: macOS .app build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install "pyinstaller>=6.10"
      
      - name: Build .app with PyInstaller
        run: |
          export PYINSTALLER_NO_SYMLINKS=1
          pyinstaller --clean --noconfirm --name "IPTV-MAC-STALKER-PLAYER" --windowed \
            --collect-submodules PyQt6 --collect-data PyQt6 \
            "STALKER PLAYER.py"


      - name: Zip the .app
        run: |
          cd dist && zip -r IPTV-MAC-STALKER-PLAYER-mac.zip "IPTV-MAC-STALKER-PLAYER.app"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IPTV-MAC-STALKER-PLAYER-mac
          path: dist/IPTV-MAC-STALKER-PLAYER-mac.zip
